extends: "../../../.nycrc.yml"
exclude:
  - "packages/cast/chain-auth/**/*.spec.ts"
include:
  - "packages/cast/chain-auth/src/**/*.ts"
extension:
  - ".ts"
cwd: "../../../"
report-dir: "reports/coverage/ut-chain-auth"
