extends: "../../../.nycrc.yml"
exclude:
  - "packages/cast/oracle-clients/**/*.spec.ts"
include:
  - "packages/cast/oracle-clients/src/**/*.ts"
extension:
  - ".ts"
cwd: "../../../"
report-dir: "reports/coverage/ut-oracle-clients"
