extends: "../../../.nycrc.yml"
exclude:
  - "packages/cast/oracles//**/*.spec.ts"
include:
  - "packages/cast/oracles//src/**/*.ts"
extension:
  - ".ts"
cwd: "../../../"
report-dir: "reports/coverage/ut-oracles"
